### ISSUE TITLE
Generic Quantifiers

### ISSUE THREAD

**Issue by HJLebbink** [nano-go/regexcv#1]
Love the library, good and comprehendible code. 

Currently, 3 quantifiers are handled:
'*': {0,inf}
'+': {1,inf}
'?': {0,1} 

**Question**: would it be complicated to handle generic quantifiers such as {1,3} in the optimization steps? I'm not sure what I would need to update.

**Comment by nano-go** [comment]
Sorry.

Do you mean to implement this quatifier?  
If so, you may require a more complex NFA to implement it.  
It may be difficult to approach this if you use DFA.

**Comment by nano-go** [comment]
Do you mean to implement this quantifier?

**Comment by HJLebbink** [comment]
Yes indeed added such generic quantifiers is reasonable more
difficult. Thanx for responding, but I've taken a different approach,
extract the NFA from golang's regex compiler. Regards HJ!

**Comment by nano-go** [comment]
Ok! Thanks!
